stages:
  - test

image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker pull kousik828/Docker-React-New:latest || true
  - docker build --cache-from kousik828/Docker-React-New:latest -t kousik828/Docker-React-New -f Dockerfile.dev .

test:
  stage: test
  script:
    - docker run -e CI=true kousik828/Docker-React-New npm run test
  after_script:
    - docker stop $(docker ps -aq)
    - docker system prune -f
